<?php

use App\Models\Company;
use App\Support\CompanyContext;

beforeEach(fn () => app(CompanyContext::class)->forget());
afterEach(fn () => app(CompanyContext::class)->forget());

/** Every admin surface must render for an authorised company member. */
dataset('adminPages', [
    'chart of accounts' => '/admin/accounts',
    'fixed assets' => '/admin/fixed-assets',
    'expenses' => '/admin/expenses',
    'reports' => '/admin/reports',
    'approvals inbox' => '/admin/approval-requests',
    'audit log' => '/admin/audit-logs',
    'customers' => '/admin/customers',
    'suppliers' => '/admin/suppliers',
    'leads' => '/admin/leads',
    'opportunities' => '/admin/opportunities',
    'pipeline' => '/admin/pipeline',
    'warehouses' => '/admin/warehouses',
    'units' => '/admin/units',
    'stock levels' => '/admin/stocks',
    'stock valuation' => '/admin/stock-valuation',
    'stock ledger' => '/admin/stock-ledger',
    'stock adjustments' => '/admin/stock-adjustments',
    'stock transfers' => '/admin/stock-transfers',
    'journals' => '/admin/journals',
    'general ledger' => '/admin/general-ledger',
    'ar aging' => '/admin/receivables-aging',
    'ap aging' => '/admin/payables-aging',
    'payments' => '/admin/payments',
    'employees' => '/admin/employees',
    'departments' => '/admin/departments',
    'designations' => '/admin/designations',
    'shifts' => '/admin/shifts',
    'attendance' => '/admin/attendances',
    'rosters' => '/admin/rosters',
    'leave types' => '/admin/leave-types',
    'leave requests' => '/admin/leave-requests',
    'payroll' => '/admin/payroll-runs',
    'holidays' => '/admin/holidays',
    'bills of materials' => '/admin/boms',
    'manufacturing orders' => '/admin/manufacturing-orders',
    'requisitions' => '/admin/purchase-requisitions',
    'rfqs' => '/admin/rfqs',
    'purchase orders' => '/admin/purchase-orders',
    'goods receipts' => '/admin/goods-receipts',
    'buying prices' => '/admin/buying-prices',
    'purchase returns' => '/admin/purchase-returns',
    'supplier invoices' => '/admin/supplier-invoices',
    'sales orders' => '/admin/sales-orders',
    'proforma invoices' => '/admin/proforma-invoices',
    'letters of credit' => '/admin/letters-of-credit',
    'commercial invoices' => '/admin/commercial-invoices',
    'packing lists' => '/admin/packing-lists',
    'export shipments' => '/admin/export-shipments',
    'delivery orders' => '/admin/delivery-orders',
    'delivery settings' => '/admin/delivery-settings',
    'quotations' => '/admin/quotations',
    'sales register' => '/admin/sales-register',
    'purchase register' => '/admin/purchase-register',
    'reports hub' => '/admin/reports-hub',
    'payment vouchers' => '/admin/payment-voucher-register',
    'receipt vouchers' => '/admin/receipt-voucher-register',
    'sales returns' => '/admin/sales-returns',
    'mrp' => '/admin/mrp',
    'production register' => '/admin/production-register',
    'wip valuation' => '/admin/wip-valuation',
    'machines' => '/admin/machines',
    'process types' => '/admin/process-types',
    'process orders' => '/admin/process-orders',
    'batches' => '/admin/batches',
    'lab dips' => '/admin/lab-dips',
    'quality inspections' => '/admin/quality-inspections',
    'production report' => '/admin/production-report',
    'material consumption report' => '/admin/material-consumption-report',
    'production wastage report' => '/admin/production-wastage-report',
    'quality report' => '/admin/quality-report',
    'production costing report' => '/admin/production-costing-report',
    'machine performance report' => '/admin/machine-performance-report',
    'pi register' => '/admin/pi-register',
    'lc register' => '/admin/lc-register',
    'lc utilization report' => '/admin/lc-utilization-report',
    'lc outstanding report' => '/admin/lc-outstanding-report',
    'export sales register' => '/admin/export-sales-register',
    'commercial invoice register' => '/admin/commercial-invoice-register',
    'shipment register' => '/admin/shipment-register',
    'customer export history' => '/admin/customer-export-history',
    'pi vs lc report' => '/admin/pi-vs-lc-report',
    'order vs pi vs lc vs shipment report' => '/admin/order-vs-pi-vs-lc-vs-shipment-report',
    'export receivable report' => '/admin/export-receivable-report',
    'notification settings' => '/admin/notification-settings',
    'users' => '/admin/users',
    'tax rates' => '/admin/tax-rates',
    'opening balances' => '/admin/opening-balances',
    'report settings' => '/admin/report-settings',
    'document library' => '/admin/documents',
]);

it('renders admin page for an authorised user', function (string $path) {
    $company = Company::factory()->create();
    $user = superAdminFor($company);

    $this->actingAs($user)->get($path)->assertOk();
})->with('adminPages');
