@extends('pdf.layout')

@php
    $money = fn ($v) => config('erp.currency.symbol').number_format((float) (string) $v, (int) config('erp.currency.precision', 2));
@endphp

@section('title', $title)
@section('period', 'Period: '.($from ?? 'Beginning').' to '.($to ?? 'Present').' · Generated by '.($generatedBy ?? 'system').' on '.now()->format('Y-m-d H:i'))

@section('content')
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Voucher / Ref</th>
                <th>{{ $partyLabel }}</th>
                <th>Method</th>
                <th>Note</th>
                <th class="num">Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($register['rows'] as $row)
                <tr>
                    <td>{{ $row['date'] }}</td>
                    <td>{{ $row['reference'] !== '' ? $row['reference'] : '—' }}</td>
                    <td>{{ $row['party'] }}</td>
                    <td>{{ $row['method'] }}</td>
                    <td>{{ $row['note'] }}</td>
                    <td class="num">{{ $money($row['amount']) }}</td>
                </tr>
            @empty
                <tr><td colspan="6">No vouchers in this period.</td></tr>
            @endforelse
            <tr class="total">
                <td colspan="5">Total ({{ $register['count'] }} vouchers)</td>
                <td class="num">{{ $money($register['total']) }}</td>
            </tr>
        </tbody>
    </table>
@endsection
