<?php

namespace App\Filament\Resources;

use App\Filament\Resources\BatchResource\Pages;
use App\Models\Batch;
use App\Models\Product;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

/**
 * Batch / lot register with full traceability. Batches are system-generated by
 * purchases and process orders, so this screen is read-only — its value is the
 * per-batch trace (where a batch came from and where it was used).
 */
class BatchResource extends Resource
{
    protected static ?string $model = Batch::class;

    protected static ?string $navigationIcon = 'heroicon-o-qr-code';

    protected static ?string $navigationGroup = 'Manufacturing';

    protected static ?string $navigationLabel = 'Batches';

    protected static ?int $navigationSort = 8;

    public static function canCreate(): bool
    {
        return false; // batches are generated by the system, never entered by hand
    }

    public static function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn ($query) => $query->with(['product', 'warehouse', 'source']))
            ->columns([
                Tables\Columns\TextColumn::make('batch_number')->searchable()->sortable(),
                Tables\Columns\TextColumn::make('product.name')->label('Product')->searchable(),
                Tables\Columns\TextColumn::make('warehouse.code')->label('Warehouse')->placeholder('—'),
                Tables\Columns\TextColumn::make('quantity')->alignRight(),
                Tables\Columns\TextColumn::make('status')->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'open' => 'success',
                        'consumed' => 'gray',
                        'on_hold' => 'warning',
                        'rejected' => 'danger',
                        default => 'gray',
                    }),
                Tables\Columns\TextColumn::make('source')->label('Origin')
                    ->state(fn (Batch $record): string => self::sourceLabel($record))->placeholder('—'),
                Tables\Columns\TextColumn::make('created_at')->date()->sortable(),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('product_id')->label('Product')
                    ->options(fn (): array => Product::query()->orderBy('name')->pluck('name', 'id')->all())
                    ->searchable(),
                Tables\Filters\SelectFilter::make('status')->options([
                    'open' => 'Open', 'consumed' => 'Consumed', 'on_hold' => 'On hold', 'rejected' => 'Rejected',
                ]),
            ])
            ->actions([
                Tables\Actions\ViewAction::make()->label('Trace'),
            ])
            ->defaultSort('id', 'desc');
    }

    /** Human label for a batch's source (e.g. "Knitting KNIT-0001", "Goods Receipt GRN-0004"). */
    public static function sourceLabel(Batch $batch): string
    {
        $source = $batch->source;
        if ($source === null) {
            return '—';
        }

        $type = str_replace('_', ' ', \Illuminate\Support\Str::snake(class_basename($batch->source_type)));
        $ref = $source->reference ?? $source->number ?? $source->code ?? ('#'.$source->getKey());

        return ucwords($type).' '.$ref;
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListBatches::route('/'),
            'view' => Pages\ViewBatch::route('/{record}'),
        ];
    }
}
