<?php

namespace App\Filament\Resources;

use App\Filament\Resources\FabricRollResource\Pages;
use App\Models\FabricRoll;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

/**
 * Individual fabric rolls produced by roll-tracked process orders. A roll is a
 * sub-division of an output batch (the batch is the stock of record); rolls give
 * roll-level traceability and QC. Read-mostly: rolls are generated by production;
 * here they are viewed, filtered and QC-marked.
 */
class FabricRollResource extends Resource
{
    protected static ?string $model = FabricRoll::class;

    protected static ?string $navigationIcon = 'heroicon-o-view-columns';

    protected static ?string $navigationGroup = 'Textile';

    protected static ?string $navigationLabel = 'Fabric Rolls';

    protected static ?int $navigationSort = 12;

    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Section::make('Roll')->columns(2)->schema([
                Forms\Components\TextInput::make('weight')->numeric()->minValue(0)->required()->suffix('KG'),
                Forms\Components\TextInput::make('length')->numeric()->minValue(0)->suffix('m'),
                Forms\Components\TextInput::make('gsm')->label('GSM'),
                Forms\Components\TextInput::make('width'),
                Forms\Components\TextInput::make('shade'),
                Forms\Components\Select::make('qc_status')->native(false)
                    ->options(['pending' => 'Pending', 'passed' => 'Passed', 'failed' => 'Failed']),
                Forms\Components\Select::make('status')->native(false)
                    ->options(['available' => 'Available', 'rejected' => 'Rejected', 'consumed' => 'Consumed']),
                Forms\Components\Textarea::make('notes')->rows(2)->columnSpanFull(),
            ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('roll_number')->label('Roll')->searchable()->sortable(),
                Tables\Columns\TextColumn::make('product.name')->label('Product')->searchable(),
                Tables\Columns\TextColumn::make('batch.batch_number')->label('Batch')->placeholder('—')->searchable(),
                Tables\Columns\TextColumn::make('processOrder.reference')->label('From order')->placeholder('—'),
                Tables\Columns\TextColumn::make('weight')->suffix(' KG')->sortable(),
                Tables\Columns\TextColumn::make('gsm')->label('GSM')->placeholder('—'),
                Tables\Columns\TextColumn::make('width')->placeholder('—'),
                Tables\Columns\TextColumn::make('qc_status')->label('QC')->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'passed' => 'success', 'failed' => 'danger', default => 'gray',
                    }),
                Tables\Columns\TextColumn::make('status')->badge()
                    ->color(fn (string $state): string => match ($state) {
                        'available' => 'success', 'rejected' => 'danger', 'consumed' => 'gray', default => 'gray',
                    }),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('qc_status')->options(['pending' => 'Pending', 'passed' => 'Passed', 'failed' => 'Failed']),
                Tables\Filters\SelectFilter::make('status')->options(['available' => 'Available', 'rejected' => 'Rejected', 'consumed' => 'Consumed']),
            ])
            ->actions([
                Tables\Actions\Action::make('pass')->label('Pass QC')->icon('heroicon-o-check')->color('success')
                    ->visible(fn (FabricRoll $r): bool => $r->qc_status !== 'passed')
                    ->action(function (FabricRoll $r): void {
                        $r->update(['qc_status' => 'passed', 'status' => 'available']);
                        Notification::make()->title('Roll passed QC')->success()->send();
                    }),
                Tables\Actions\Action::make('fail')->label('Fail QC')->icon('heroicon-o-x-mark')->color('danger')
                    ->visible(fn (FabricRoll $r): bool => $r->qc_status !== 'failed')
                    ->requiresConfirmation()
                    ->action(function (FabricRoll $r): void {
                        $r->update(['qc_status' => 'failed', 'status' => 'rejected']);
                        Notification::make()->title('Roll rejected')->danger()->send();
                    }),
                Tables\Actions\EditAction::make(),
            ])
            ->defaultSort('id', 'desc');
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageFabricRolls::route('/'),
        ];
    }
}
